version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: adsky_postgres
    environment:
      POSTGRES_USER: adsky_user
      POSTGRES_PASSWORD: adsky_password
      POSTGRES_DB: adsky_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
